
import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sandy
 */
public class FrmBuscarClientes extends javax.swing.JFrame {

    public  String sql = "";
    
    public FrmBuscarClientes() {
        initComponents();
         mostrardatos("");
          this.setLocationRelativeTo(null);
    }
    void mostrardatos(String buscar){
         
         buscar=txtBuscar.getText();
        
        DefaultTableModel modelo = new DefaultTableModel();
         modelo.addColumn("ID");
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Email");
        modelo.addColumn("Direccion");
       
        Tabla2.setModel(modelo);

        
       
        
        if (sql.equals("")){
            sql="SELECT ID,Cedula,Nombre,Telefono,Email,DIreccion FROM clientes";
        }
        
       
        
        if(rbCedula.isSelected()){
            sql="SELECT * FROM clientes WHERE Cedula ='"+buscar+"'";
            
        }else if(rbNombre.isSelected()){
             sql="SELECT * FROM clientes WHERE Nombre ='"+buscar+"'";
        }
            
             if (buscar.equals("")){
             sql="SELECT ID,Cedula,Nombre,Telefono,Email,DIreccion FROM clientes";

        }
        
        String [] dato = new String [6];
        
        try {
           Statement st = cn.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
           while(rs.next()){
               
               dato[0] = rs.getString(1);
               dato[1] = rs.getString(2);
               dato[2] = rs.getString(3);
               dato[3] = rs.getString(4);
               dato[4] = rs.getString(5);
               dato[5] = rs.getString(6);
               
               modelo.addRow(dato);
               Tabla2.setModel(modelo);
           }
      
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        rbNombre = new javax.swing.JRadioButton();
        rbCedula = new javax.swing.JRadioButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        btnObtener = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Listado de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 230, 20));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(36, 47, 65));
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 320, 30));

        rbNombre.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(rbNombre);
        rbNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbNombre.setForeground(new java.awt.Color(153, 153, 153));
        rbNombre.setText("Nombre");
        jPanel1.add(rbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 90, -1));

        rbCedula.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(rbCedula);
        rbCedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbCedula.setForeground(new java.awt.Color(153, 153, 153));
        rbCedula.setText("Cedula");
        jPanel1.add(rbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(97, 112, 195));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(97, 112, 195));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete_50px.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 110, 60));

        btnBuscar.setBackground(new java.awt.Color(97, 112, 195));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(97, 112, 195));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search_50px.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 110, 60));

        btnActualizar.setBackground(new java.awt.Color(97, 112, 195));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(97, 112, 195));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Edit File_50px.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 110, 60));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 430, 10));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Filtrar Busqueda de Clientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 750, 170));

        btnObtener.setBackground(new java.awt.Color(97, 112, 195));
        btnObtener.setForeground(new java.awt.Color(97, 112, 195));
        btnObtener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Set As Resume_50px.png"))); // NOI18N
        btnObtener.setBorder(null);
        btnObtener.setEnabled(false);
        btnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActionPerformed(evt);
            }
        });
        jPanel1.add(btnObtener, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 110, 60));

        btnSalir.setBackground(new java.awt.Color(97, 112, 195));
        btnSalir.setForeground(new java.awt.Color(97, 112, 195));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit_50px.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 110, 60));

        jButton1.setBackground(new java.awt.Color(97, 112, 195));
        jButton1.setForeground(new java.awt.Color(97, 112, 195));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Refresh_24px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 122, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(txtBuscar.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Introduzca un valor de busqueda");
            
        }
        mostrardatos(txtBuscar.getText());
          //txtBuscar.setText("");
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        FrmClientes clientes= new FrmClientes();
        FrmClientes.btnActualizar.setEnabled(true);
        FrmClientes.btnGuardar.setEnabled(false);
        clientes.setVisible(true);
        
       int fila = Tabla2.getSelectedRow();
        
        FrmClientes.txtCedula.setText(Tabla2.getValueAt(fila, 1).toString());
        FrmClientes.txtNombre.setText(Tabla2.getValueAt(fila, 2).toString());
        FrmClientes.txtTelefono.setText(Tabla2.getValueAt(fila, 3).toString());
        FrmClientes.txtEmail.setText(Tabla2.getValueAt(fila, 4).toString());
        FrmClientes.txtDireccion.setText(Tabla2.getValueAt(fila, 5).toString());
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
          int fila = (Tabla2.getSelectedRow());
         
        if (fila >=0){
     
         String titulo = (String) Tabla2.getValueAt(fila,0);
         
            int ax = JOptionPane.showConfirmDialog(null, "Estas seguro que desea eliminar este cliente?");
              if(ax == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, "EL Cliente fue eliminado con éxito!!!");
                 try {
                PreparedStatement pst = cn.prepareStatement("DELETE from clientes where  ID = '"+titulo+"'");
                pst.executeUpdate();
                
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

              
            }
            else if(ax == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "No se elimino el libro");
            }
               
             mostrardatos("");
        }
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerActionPerformed
        // TODO add your handling code here:
  
     
        
      
         int fila = Tabla2.getSelectedRow();
        FrmPrestamo.txtCedula.setText(Tabla2.getValueAt(fila, 1).toString());
        FrmPrestamo.txtNombre.setText(Tabla2.getValueAt(fila, 2).toString());
       dispose();
        
        
     

    }//GEN-LAST:event_btnObtenerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
           txtBuscar.setText("");
               mostrardatos("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
             int ax =JOptionPane.showConfirmDialog(null, "Estas seguro que desea Salir?");
          if(ax == JOptionPane.YES_OPTION){
              JOptionPane.showMessageDialog(null, "Saliendo");
              dispose();
              
          }  else if(ax == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "Cancelado");
            }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla2;
    public static javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    public static javax.swing.JButton btnObtener;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbCedula;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
ConexionSQL ir = new ConexionSQL();
    Connection cn = ir.conexion();
}

