
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sandy
 */
public class FrmBuscarLibros extends javax.swing.JFrame {

      public  String sql = "";
      
    public FrmBuscarLibros() {
        initComponents();
           this.setLocationRelativeTo(null);
            mostrardatos("");
    }
    void salir(){
          int ax =JOptionPane.showConfirmDialog(null, "Estas seguro que desea Salir?");
          if(ax == JOptionPane.YES_OPTION){
              JOptionPane.showMessageDialog(null, "Saliendo");
              dispose();
              
          }  else if(ax == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "Cancelado");
            }
}
    void mostrardatos(String buscar){
         
         buscar=txtBuscar.getText();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("Editorial");
        modelo.addColumn("Paginas");
        modelo.addColumn("Stock");
        modelo.addColumn("Categorias");
        Tabla3.setModel(modelo);

        
       
       if(rbTitulo.isSelected()){
               sql="SELECT * FROM libros WHERE Titulo ='"+buscar+"'";
            
        }else if(rbAutor.isSelected()){
             sql="SELECT * FROM libros WHERE Autor ='"+buscar+"'";
        }
            
            if (buscar.equals("")){
             sql="SELECT Codigo,Titulo,Autor,Editorial,Paginas,Stock,Categoria FROM libros";

        }
        
        String [] dato = new String [7];
        
        try {
           Statement st = cn.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
           while(rs.next()){
               
               dato[0] = rs.getString(1);
               dato[1] = rs.getString(2);
               dato[2] = rs.getString(3);
               dato[3] = rs.getString(4);
               dato[4] = rs.getString(5);
               dato[5] = rs.getString(6);
               dato[6] = rs.getString(7);
               modelo.addRow(dato);
               Tabla3.setModel(modelo);
           }
      
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        rbAutor = new javax.swing.JRadioButton();
        rbTitulo = new javax.swing.JRadioButton();
        btnObtener = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 760, 210));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Listado de Libros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 210, 20));

        btnBuscar.setBackground(new java.awt.Color(97, 112, 195));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(36, 47, 65));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search_50px.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 110, 60));

        btnActualizar.setBackground(new java.awt.Color(97, 112, 195));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(36, 47, 65));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Edit File_50px.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 110, 60));

        btnEliminar.setBackground(new java.awt.Color(97, 112, 195));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(36, 47, 65));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete_50px.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 110, 60));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 430, 20));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Filtrar Busqueda de Libros");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 20));

        txtBuscar.setBackground(new java.awt.Color(36, 47, 65));
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 270, 30));

        rbAutor.setBackground(new java.awt.Color(36, 47, 65));
        rbAutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbAutor.setForeground(new java.awt.Color(153, 153, 153));
        rbAutor.setText("Autor");
        rbAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAutorActionPerformed(evt);
            }
        });
        jPanel1.add(rbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, -1));

        rbTitulo.setBackground(new java.awt.Color(36, 47, 65));
        rbTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbTitulo.setForeground(new java.awt.Color(153, 153, 153));
        rbTitulo.setText("Titulo");
        jPanel1.add(rbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, -1));

        btnObtener.setBackground(new java.awt.Color(97, 112, 195));
        btnObtener.setForeground(new java.awt.Color(97, 112, 195));
        btnObtener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Set As Resume_50px.png"))); // NOI18N
        btnObtener.setBorder(null);
        btnObtener.setEnabled(false);
        btnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActionPerformed(evt);
            }
        });
        jPanel1.add(btnObtener, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 110, 60));

        btnSalir.setBackground(new java.awt.Color(97, 112, 195));
        btnSalir.setForeground(new java.awt.Color(97, 112, 195));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit_50px.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 110, 60));

        jButton1.setBackground(new java.awt.Color(97, 112, 195));
        jButton1.setForeground(new java.awt.Color(97, 112, 195));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Refresh_24px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 50, 40));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         mostrardatos(txtBuscar.getText());
          txtBuscar.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        FrmLibros2 libros= new  FrmLibros2();
         FrmLibros2.btnActualizar.setEnabled(true);
        FrmLibros2.btnGuardar.setEnabled(false);
        libros.setVisible(true);
        
     
        
       int fila = Tabla3.getSelectedRow();
       
        FrmLibros2.txtTitulo.setText(Tabla3.getValueAt(fila, 1).toString());
        FrmLibros2.txtAutor.setText(Tabla3.getValueAt(fila, 2).toString());
        FrmLibros2.txtEditorial.setText(Tabla3.getValueAt(fila, 3).toString());
        FrmLibros2.txtPaginas.setText(Tabla3.getValueAt(fila, 4).toString());
        FrmLibros2.txtStock.setText(Tabla3.getValueAt(fila, 5).toString());
        FrmLibros2.txtCategoria.setText(Tabla3.getValueAt(fila, 6).toString());
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        int fila = (Tabla3.getSelectedRow());
       String titulo = (String) Tabla3.getValueAt(fila,0);
        if (fila >=0){
            
            
             int ax = JOptionPane.showConfirmDialog(null, "Estas seguro que desea eliminar este libro?");
              if(ax == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, "EL Libro fue eliminado con éxito!!!");
                 try {
                PreparedStatement pst = cn.prepareStatement("DELETE from libros where  Codigo = '"+titulo+"'");
                pst.executeUpdate();
                
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

              
            }
            else if(ax == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "No se elimino el libro");
            }
              mostrardatos("");

          

           

        }
        
           
           
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        // TODO add your handling code here:
    
         mostrardatos("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void btnObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerActionPerformed
        // TODO add your handling code here:


        int fila = Tabla3.getSelectedRow();
        if (fila>= 0){
        FrmPrestamo.txtCodigo.setText(Tabla3.getValueAt(fila, 0).toString());
        FrmPrestamo.txtTitulo.setText(Tabla3.getValueAt(fila, 1).toString());
        dispose();}else{
            JOptionPane.showMessageDialog(null, "No haSeleccionado un elemento");
        }
       
    }//GEN-LAST:event_btnObtenerActionPerformed

    private void rbAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAutorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        txtBuscar.setText("");
        mostrardatos("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre;
        
        nombre = (eliminar.nombre);
        System.out.println(nombre);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla3;
    public static javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    public static javax.swing.JButton btnObtener;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbAutor;
    private javax.swing.JRadioButton rbTitulo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

ConexionSQL ir = new ConexionSQL();
    Connection cn = ir.conexion();
}
