
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sandy
 */
public class FrmDevolucion extends javax.swing.JFrame {
  String n_libro;
      public  String sql = "";
    public FrmDevolucion() {
        initComponents();
         mostrardatos("");
           this.setLocationRelativeTo(null);
    }
      void mostrardatos(String buscar){
         
         buscar=txtBuscar.getText();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Ingreso#");
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Titulo");
        modelo.addColumn("Codigo");
        modelo.addColumn("Fecha Prestamo");
        modelo.addColumn("Fecha Entrega");
      
       
        Tabla5.setModel(modelo);
        
        if (sql.equals("")){
            sql="SELECT Ingreso,Cedula,Nombre,Titulo,Codigo,Fecha_Prestamo,Fecha_Entrega FROM prestamo";
        }else{
             sql="SELECT * FROM prestamo WHERE Cedula ='"+buscar+"'";

        }if (buscar.equals("")){
            sql="SELECT Ingreso,Cedula,Nombre,Titulo,Codigo,Fecha_Prestamo,Fecha_Entrega FROM prestamo";
        }
        
           String [] dato = new String [7];
        try {
           Statement st = cn.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
           while(rs.next()){
               
               dato[0] = rs.getString(1);
               dato[1] = rs.getString(2);
               dato[2] = rs.getString(3);
               dato[3] = rs.getString(4);
               dato[4] = rs.getString(5);
               dato[5] = rs.getString(6);
               dato[6] = rs.getString(7);
               
               
               modelo.addRow(dato);
               Tabla5.setModel(modelo);
           }
      
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla5 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla5);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 870, 250));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Ingrese Cedula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 230, -1));

        btnBuscar.setBackground(new java.awt.Color(97, 112, 195));
        btnBuscar.setForeground(new java.awt.Color(97, 112, 195));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search_50px.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 110, 60));

        btnDevolucion.setBackground(new java.awt.Color(97, 112, 195));
        btnDevolucion.setForeground(new java.awt.Color(97, 112, 195));
        btnDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Return Purchase_50px.png"))); // NOI18N
        btnDevolucion.setBorder(null);
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 110, 60));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Gestionar Devoluciones");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 300, -1));

        btnSalir.setBackground(new java.awt.Color(97, 112, 195));
        btnSalir.setForeground(new java.awt.Color(97, 112, 195));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exit_50px.png"))); // NOI18N
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 110, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        mostrardatos(txtBuscar.getText());
        txtBuscar.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        // TODO add your handling code here:
             int fila = (Tabla5.getSelectedRow());
         
        if (fila >=0){
     
         String titulo = (String) Tabla5.getValueAt(fila,4);
         
            int ax = JOptionPane.showConfirmDialog(null, "Estas seguro que desea eliminar este cliente?");
              if(ax == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, "EL Cliente fue eliminado con éxito!!!");
                 try {
                PreparedStatement pst = cn.prepareStatement("DELETE from prestamo where  Codigo = '"+titulo+"'");
                pst.executeUpdate();
                
                   /////////////////////////////////////////////////////////////////////////////////////////////////////////////      
          PreparedStatement ps = cn.prepareStatement("SELECT Stock FROM libros WHERE Codigo = '"+titulo+"'");
           ResultSet st= ps.executeQuery();
        
        if (st.next()){
         n_libro = st.getString("Stock");
        }
        
                 

        int numero_libro = Integer.parseInt(n_libro);
        numero_libro = numero_libro + 1;
           String num = String.valueOf(numero_libro);
           
   PreparedStatement up = cn.prepareStatement("UPDATE libros SET Stock = '"+num+"' WHERE codigo = '"+titulo+"'");
       up.executeUpdate();
   //////////////////////////////////////////////////////////////////////////////////////////////////////////////////   
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
              }    
        }
    }//GEN-LAST:event_btnDevolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla5;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
ConexionSQL ir = new ConexionSQL();
    Connection cn = ir.conexion();
}