
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sandy
 */
public class FrmLibros extends javax.swing.JFrame {

  public  String sql = "";
   
    public FrmLibros()  {
        initComponents();
   
     this.setLocationRelativeTo(null);
      
      
       mostrardatos("");
       
       
       
    }
     void mostrardatos(String buscar){
         
         buscar=txtBtitulo.getText();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("Editorial");
        modelo.addColumn("Paginas");
        modelo.addColumn("Stock");
        modelo.addColumn("Categorias");
        Tabla.setModel(modelo);

        
       
        
        if (sql.equals("")){
            sql="SELECT Codigo,Titulo,Autor,Editorial,Paginas,Stock,Categoria FROM libros";
        }else{
             sql="SELECT * FROM libros WHERE Titulo ='"+buscar+"'";

        }if (buscar.equals("")){
             sql="SELECT Codigo,Titulo,Autor,Editorial,Paginas,Stock,Categoria FROM libros";

        }
        
        String [] dato = new String [7];
        
        try {
           Statement st = cn.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
           while(rs.next()){
               
               dato[0] = rs.getString(1);
               dato[1] = rs.getString(2);
               dato[2] = rs.getString(3);
               dato[3] = rs.getString(4);
               dato[4] = rs.getString(5);
               dato[5] = rs.getString(6);
               dato[6] = rs.getString(7);
               modelo.addRow(dato);
               Tabla.setModel(modelo);
           }
      
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        txtBtitulo = new javax.swing.JTextField();
        txtBautor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jMenuItem1.setText("ELIMINAR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(Tabla);

        jTabbedPane1.addTab("Lista de Libros", jScrollPane1);

        jPanel3.setMaximumSize(new java.awt.Dimension(635, 152));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Titulo");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 40, -1, -1));

        jLabel8.setText("Autor");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 78, -1, -1));
        jPanel3.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 36, 139, -1));
        jPanel3.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 82, 139, -1));
        jPanel3.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 112, 139, -1));
        jPanel3.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 36, 160, -1));
        jPanel3.add(txtPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 82, 160, -1));
        jPanel3.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 128, 160, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 78, -1, -1));

        jLabel9.setText("Editorial");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 116, -1, -1));

        jLabel12.setText("Categoria");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 40, -1, -1));

        jLabel13.setText("Paginas");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 86, -1, -1));

        jLabel14.setText("Stock");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 128, -1, -1));

        jTabbedPane1.addTab("Mantenimiento", jPanel3);

        jInternalFrame2.setTitle("Buscar Libros");
        jInternalFrame2.setVisible(true);

        jLabel10.setText("Titulo");

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel11.setText("Autor");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtBautor))
                .addGap(34, 34, 34)
                .addComponent(btnBuscar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtBtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnBuscar1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 830, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fila = (Tabla.getSelectedRow());
         
        if (fila >=0){
     
         String titulo = (String) Tabla.getValueAt(fila,1);
         
            try {
                PreparedStatement pst = cn.prepareStatement("DELETE from libros where  Titulo = '"+titulo+"'");
                pst.executeUpdate();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
               

        }
        mostrardatos("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        mostrardatos(txtBautor.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        
         try {
            PreparedStatement pst  = cn.prepareStatement("INSERT INTO libros(Titulo,Autor,Editorial,Paginas,Stock,Categoria)values(?,?,?,?,?,?)");
            pst.setString(1, txtTitulo.getText());
            pst.setString(2, txtAutor.getText());
            pst.setString(3, txtEditorial.getText());
            pst.setString(4, txtPaginas.getText());
            pst.setString(5, txtStock.getText());
            pst.setString(6, txtCategoria.getText());
            pst.executeUpdate();

            int ax = JOptionPane.showConfirmDialog(null, "Estas seguro de agregar este libro?");
            if(ax == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, "EL Libro fue agregado con éxito!!!");

                txtTitulo.setText("");
                txtAutor.setText("");
                txtEditorial.setText("");
                txtPaginas.setText("");
                txtStock.setText("");
                txtCategoria.setText("");

            }
            else if(ax == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "No se agrego el libro");
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        mostrardatos("");
                                      
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      //</editor-fold>
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmLibros().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBautor;
    private javax.swing.JTextField txtBtitulo;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
ConexionSQL ir = new ConexionSQL();
    Connection cn = ir.conexion();
}
