/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author Sandy
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
  
    public Inicio() {
        initComponents();
           this.setLocationRelativeTo(null);
                   
                   
                    
    }
    
 
 
  
 
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLibros = new javax.swing.JButton();
        btnBuscarlibros = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnBuscarClientes = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarClientes1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 70));
        jPanel2.setForeground(new java.awt.Color(36, 47, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(36, 47, 65));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("System ");
        jLabel1.setInheritsPopupMenu(false);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -40, -1, 137));

        lbHora.setBackground(new java.awt.Color(153, 153, 153));
        lbHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHora.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 82, 39));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1010, 130));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLibros.setBackground(new java.awt.Color(97, 112, 195));
        btnLibros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLibros.setForeground(new java.awt.Color(204, 204, 255));
        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Books_50px.png"))); // NOI18N
        btnLibros.setText("Añadir");
        btnLibros.setBorder(null);
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 152, 84));

        btnBuscarlibros.setBackground(new java.awt.Color(97, 112, 195));
        btnBuscarlibros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarlibros.setForeground(new java.awt.Color(204, 204, 204));
        btnBuscarlibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Book Shelf_50px.png"))); // NOI18N
        btnBuscarlibros.setText("Listado");
        btnBuscarlibros.setBorder(null);
        btnBuscarlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarlibrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarlibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 152, 84));

        btnClientes.setBackground(new java.awt.Color(97, 112, 195));
        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(204, 204, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add User Male_50px.png"))); // NOI18N
        btnClientes.setText("Añadir");
        btnClientes.setBorder(null);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 152, 84));

        btnBuscarClientes.setBackground(new java.awt.Color(97, 112, 195));
        btnBuscarClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarClientes.setForeground(new java.awt.Color(204, 204, 255));
        btnBuscarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Find User Male_50px.png"))); // NOI18N
        btnBuscarClientes.setText("Buscar");
        btnBuscarClientes.setBorder(null);
        btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 152, 84));

        btnPrestar.setBackground(new java.awt.Color(97, 112, 195));
        btnPrestar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrestar.setForeground(new java.awt.Color(204, 204, 255));
        btnPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buy_50px.png"))); // NOI18N
        btnPrestar.setText("Prestamo");
        btnPrestar.setBorder(null);
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 152, 84));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1010, 220));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setForeground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(36, 47, 65));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Library");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 182, -1));

        btnBuscarClientes1.setBackground(new java.awt.Color(36, 47, 70));
        btnBuscarClientes1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarClientes1.setForeground(new java.awt.Color(36, 47, 70));
        btnBuscarClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout Rounded Up_50px.png"))); // NOI18N
        btnBuscarClientes1.setBorder(null);
        btnBuscarClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientes1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 100, 64));

        jLabel3.setBackground(new java.awt.Color(36, 47, 65));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Salir");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 55, -1));

        lbFecha.setBackground(new java.awt.Color(153, 153, 153));
        lbFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 92, 31));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarlibrosActionPerformed
        // TODO add your handling code here:
        
        FrmBuscarLibros libros= new FrmBuscarLibros ();
        libros.setVisible(true);
        
        
    }//GEN-LAST:event_btnBuscarlibrosActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        // TODO add your handling code here:
        FrmLibros2 libros= new FrmLibros2();
        libros.setVisible(true);
        FrmLibros2.btnActualizar.setEnabled(false);
        
        
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
        // TODO add your handling code here:
        FrmBuscarClientes clientes= new FrmBuscarClientes();
        clientes.setVisible(true);
       
    }//GEN-LAST:event_btnBuscarClientesActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        FrmClientes clientes= new FrmClientes();
        clientes.setVisible(true);
        FrmClientes.btnActualizar.setEnabled(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnBuscarClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientes1ActionPerformed
        // TODO add your handling code here:
            int ax =JOptionPane.showConfirmDialog(null, "Estas seguro que desea salir del sistema?");
          if(ax == JOptionPane.YES_OPTION){
              JOptionPane.showMessageDialog(null, "Saliendo");
            System.exit(0);
              
          }  else if(ax == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "Cancelado");
            }
    }//GEN-LAST:event_btnBuscarClientes1ActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
        FrmPrestamo prestar = new FrmPrestamo();
        prestar.setVisible(true);
    }//GEN-LAST:event_btnPrestarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarClientes;
    private javax.swing.JButton btnBuscarClientes1;
    private javax.swing.JButton btnBuscarlibros;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lbFecha;
    public static javax.swing.JLabel lbHora;
    // End of variables declaration//GEN-END:variables
}
